package me.vladosik.csu.config;

import com.google.gson.*;
import me.vladosik.csu.CodespaceUtils;
import me.vladosik.csu.utils.Utils;
import net.minecraft.client.player.LocalPlayer;
import net.minecraft.core.Holder;
import net.minecraft.core.component.DataComponents;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.Style;
import net.minecraft.resources.Identifier;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.EquipmentSlotGroup;
import net.minecraft.world.entity.ai.attributes.Attribute;
import net.minecraft.world.entity.ai.attributes.AttributeModifier;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.component.ItemAttributeModifiers;
import net.minecraft.world.item.component.ItemLore;
import net.minecraft.world.item.equipment.Equippable;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.List;
import java.util.Map;

public class Config {
    public final JsonObject json;

    public final int maxPacketsPerSecond;

    public final File primaryArrangement;
    public final boolean applyArrangementOnJoin;
    public final int delayBeforeAutoApply;

    public final boolean teleportOnGlassBreak;
    public final TeleportationType teleportationType;
    public final MovementMultiplier movementMultiplier;

    public final boolean debugMessagesEnabled;
    public final boolean debugDisablePacketQueue;

    public static Config ofConfigJSON() throws RuntimeException {
        String content;
        try {
            content = Files.readString(CodespaceUtils.getConfigFile().toPath());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return new Config(JsonParser.parseString(content).getAsJsonObject());
    }

    public Config(JsonObject json) throws ClassCastException, NullPointerException, NumberFormatException, IllegalStateException, JsonSyntaxException {
        this.json = json;

        JsonObject common = json.getAsJsonObject("common");
        maxPacketsPerSecond = common.get("max-packets-per-second").getAsInt();

        JsonObject inventory = json.getAsJsonObject("inventory");
        primaryArrangement = new File(CodespaceUtils.getArrangementsDir(), inventory.get("primary").getAsString());
        applyArrangementOnJoin = inventory.get("apply-on-join").getAsBoolean();
        delayBeforeAutoApply = inventory.get("delay-on-auto-apply").getAsInt();

        JsonObject nav = json.getAsJsonObject("navigation");
        teleportOnGlassBreak = nav.get("teleport-on-glass-break").getAsBoolean();
        teleportationType = TeleportationType.valueOf(nav.get("teleporting-method").getAsString());
        movementMultiplier = new Gson().fromJson(nav.getAsJsonObject("movement-multiplier"), MovementMultiplier.class);

        JsonObject debug = json.getAsJsonObject("debug");
        debugMessagesEnabled = debug.get("messages").getAsBoolean();
        debugDisablePacketQueue = debug.get("disable-packet-queue").getAsBoolean();
    }

    public void write() {
        Gson gson = new GsonBuilder().setFormattingStyle(FormattingStyle.PRETTY.withIndent("  ")).create();
        try {
            Files.writeString(CodespaceUtils.getConfigFile().toPath(), gson.toJson(json));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public Config copy() {
        return new Config(json);
    }

    public record MovementMultiplier(boolean enable, boolean hidden, int movement, int sneaking) {
        private static final ItemLore LORE = new ItemLore(List.of(
            Component.literal("This item was generated by Codespace Utils mod").withStyle(Style.EMPTY.withItalic(false).withColor(Utils.COLOR_WHITE)),
            Component.literal("https://github.com/kalienda/codespace-utils").withStyle(Style.EMPTY.withItalic(false).withColor(Utils.COLOR_WHITE))
        ));

        public ItemStack assemble() {
            if (!enable) return ItemStack.EMPTY;
            ItemStack is = new ItemStack(hidden ? Items.POLISHED_BLACKSTONE_BUTTON : Items.LEATHER_BOOTS);
            if (hidden) is.set(DataComponents.EQUIPPABLE, Equippable.builder(EquipmentSlot.FEET)
                .setAllowedEntities(EntityType.PLAYER)
                .setEquipOnInteract(true)
                .build()
            );

            Map<Holder<Attribute>, AttributeModifier> modifiers = Map.of(
                Attributes.MOVEMENT_SPEED, new AttributeModifier(Identifier.withDefaultNamespace("movement_speed"), movement/100f, AttributeModifier.Operation.ADD_MULTIPLIED_BASE),
                Attributes.SNEAKING_SPEED, new AttributeModifier(Identifier.withDefaultNamespace("sneaking_speed"), sneaking/100f, AttributeModifier.Operation.ADD_MULTIPLIED_BASE)
            );

            ItemAttributeModifiers.Builder builder = ItemAttributeModifiers.builder();
            modifiers.forEach((k, v) -> {
                if (v.amount() == 0) return;
                builder.add(k, v, EquipmentSlotGroup.FEET);
            });
            is.set(DataComponents.ATTRIBUTE_MODIFIERS, builder.build());
            is.set(DataComponents.LORE, LORE);
            return is;
        }
    }

    public enum TeleportationType {
        PACKET, COMMAND;

        public void move(LocalPlayer player, double x, double y, double z) {
            switch (this) {
                case PACKET -> player.snapTo(x, y, z);
                case COMMAND -> player.connection.sendCommand("tp %f %f %f".formatted(x, y, z));
            }
        }
    }
}
